kir-dev/cmsch

src/main/client/README.md
src/main/client/src/components/@commons/Basics.tsx
src/main/client/src/components/@layout/Page.tsx
src/main/client/src/components/@pages/CommunityList.tsx
src/main/client/src/components/@pages/CommunityPage.tsx
src/main/client/src/components/@pages/Home.tsx
src/main/client/src/components/@pages/ResortList.tsx
src/main/client/src/components/@pages/ResortPage.tsx
src/main/client/src/utils/customTheme.ts

- React FC components
- Page component (Container + Outlet)
- Paragraph component (Text with margin Y)
- Heading and Text global styling
- Starter pages now use Page component and Heading

Basic components

---

src/main/client/src/components/@commons/Warning.tsx
src/main/client/src/components/@layout/IndexLayout.tsx
src/main/client/src/types/dto/warning.ts

Displays message from the warning endpoint of the api. Issue #40

Add warning component

---

src/main/resources/banner.txt

Generated with https://devops.datenkollektiv.de/banner.txt/index.html with the great `starwars` banner font

Add fun custom banner txt

---

README.md
build.gradle.kts
src/main/client/README.md
src/main/client/package.json
src/main/client/yarn.lock

Easier building workflow for VSCode devs

---

src/main/client/src/components/@commons/AchievementCategoryItem.tsx
src/main/client/src/components/@pages/AchievementList.tsx
src/main/client/src/components/@pages/AchievementPage.tsx
src/main/client/src/types/dto/achievements.ts
src/main/kotlin/hu/bme/sch/cmsch/config/TestConfig.kt

I think this should work, but I couldn't test it properly because the API calls to /achievement respond with almost no data (as if there were no categories or achievements), even though I can see mock data in the admin.  Is that feature not ready on the backend or did I set up the backend incorrectly? There are also some styling changes to be made.

Bucketlist API implementation

---

src/main/client/src/App.tsx
src/main/client/src/components/@layout/Page.tsx
src/main/client/src/components/@pages/RiddleCategoryList.tsx
src/main/client/src/components/@pages/RiddlePage.tsx
src/main/client/src/utils/Loading.tsx
src/main/client/src/utils/navItems.ts

This should resolve the failing build on `master`

CMSCH #117 Remove unused imports and reintroduce missing Context

---

src/main/client/src/components/@pages/RiddleCategoryList.tsx
src/main/client/src/components/@pages/RiddlePage.tsx
src/main/client/src/utils/configurations.ts

add basic riddle pages

---

src/main/client/src/components/@commons/Warning.tsx
src/main/client/src/components/@pages/AchievementList.tsx
src/main/client/src/components/@pages/AchievementPage.tsx
src/main/client/src/components/@pages/Home.tsx
src/main/client/src/components/@pages/ProfilePage.tsx
src/main/client/src/components/@pages/QRList.tsx
src/main/client/src/components/@pages/QRScan.tsx
src/main/client/src/components/@pages/QRScanResult.tsx
src/main/client/src/components/@pages/RiddleCategoryList.tsx
src/main/client/src/components/@pages/RiddlePage.tsx
src/main/client/src/utils/navItems.ts

- Added loading component to pages that use API calls.
- Added error handling to those calls throught ServiceContext
- AuthContext will log you out if the profile call fails on appear (it means that the session is invalid)
This update connects almost everything we did until this point.

Loading and service context implementation alias Ecosystem Update

---

src/main/client/src/components/@commons/AuthButton.tsx
src/main/client/src/components/@layout/navigation/DesktopNav.tsx
src/main/client/src/components/@layout/navigation/MobileNav.tsx
src/main/client/src/components/@pages/ProfilePage.tsx
src/main/client/src/types/NavItem.ts
src/main/client/src/utils/navItems.ts

See commit messages for **What's new**
Closes #130

CMSCH #130 Solve navbar problems

---

src/main/client/src/components/@layout/Footer.tsx
src/main/client/src/content/socialPages.ts
src/main/client/src/types/SocialPage.ts
src/main/client/src/utils/configurations.ts
src/main/client/src/utils/customTheme.ts

Not great, not terrible
Waiting for better ideas
Closes #94

Footer update

---

src/main/client/src/App.tsx
src/main/client/src/components/@pages/ImpressumPage.tsx
src/main/client/src/content/devs.ts
src/main/client/src/types/Dev.ts
src/main/client/src/utils/configurations.ts

To avoid merge conflicts, the link in the footer will be added later in the footer update.
Closes #121

Impressum page

---

src/main/client/src/App.tsx
src/main/client/src/global.css

Customize scrollbar on chome

---

src/main/client/src/components/@commons/StampComponent.tsx
src/main/client/src/components/@pages/QRList.tsx
src/main/client/src/components/@pages/QRScan.tsx
src/main/client/src/utils/Loading.tsx

A few improvements happened in this pr:
- Added info box on token collection
- removed todo text
- removed types from stamp
- improved spacing
- used common components like Loading, and ServiceContext throw error
- fixed a little bug in the common loading component
- improved the stamp colors, so they are more inline with the style of the page and better to look at in night mode 
closes #66

Improve QR page

---

src/main/client/src/components/@commons/YouTubeFrame.tsx
src/main/client/src/components/@layout/IndexLayout.tsx
src/main/client/src/components/@layout/navigation/MobileNav.tsx
src/main/client/src/components/@pages/CommunityList.tsx
src/main/client/src/components/@pages/CommunityPage.tsx
src/main/client/src/components/@pages/Home.tsx
src/main/client/src/content/communities.ts
src/main/client/src/types/Organization.ts
src/main/client/src/utils/ScrollToTop.tsx

- Search is now expanded to interests, id and custom keywords
- YouTube frame is added and is responsive
- Added required text in quote marks to main site
- Added scroll to top
- Fixed mobile nav subitems not navigation when clicking outside the text

It fixes a bunch of stuff

---

src/main/client/src/components/@commons/CustomBreadcrumb.tsx
src/main/client/src/components/@pages/CommunityPage.tsx
src/main/client/src/components/@pages/ResortPage.tsx

the colors might be a bit too much, what do you guys think?
Closes #158

Breadcrumbs at resort and community pages

---

src/main/client/src/components/@pages/ImpressumPage.tsx

update impr white kirdev

---

src/main/client/src/components/@pages/AchievementPage.tsx

Accept attribute fix

---

src/main/client/src/components/@pages/RiddleCategoryList.tsx
src/main/client/src/components/@pages/RiddlePage.tsx

- Riddle lis page:
- add translate to list items
- update hover colors and cursor
- handle missing progress border on 0/0
- Riddle page 
- add breadcrumbs
- hide image if not specified
- close error toast if another is opened

update riddle pages

---

src/main/client/src/components/@commons/CardListItem.tsx
src/main/client/src/components/@commons/DataSheet.tsx
src/main/client/src/components/@commons/Warning.tsx
src/main/client/src/components/@layout/navigation/DesktopNav.tsx
src/main/client/src/components/@pages/Home.tsx
src/main/client/src/components/@pages/ProfilePage.tsx
src/main/client/src/content/communities.ts
src/main/client/src/types/Organization.ts
src/main/client/src/types/dto/warning.ts

Closes issues I linked
- Warning message
- Logout button
- Dark mode organization logo
- Chevron down on menuIten
- ...

Small features 01.28

---

src/main/client/src/components/@commons/PresenceAlert.tsx
src/main/client/src/components/@pages/ProfilePage.tsx
src/main/client/src/components/@pages/QRList.tsx
src/main/client/src/types/dto/profile.ts

- We implemented a multi color progress circle to indicate the submittted and and completed percents separately.
- Submitted percent is not displayed when zero

add multicolor progress circle

---

src/main/client/src/global.css

Light mode:
Light mode hover:
Dark mode:
Dark mode hover:
Closes #172

Scrollbar update

---

src/main/client/src/components/@layout/Footer.tsx
src/main/client/src/components/@pages/ImpressumPage.tsx

Requested changes.
Closes #198 
Closes #197 
Closes #191

Impressum fixes

---

src/main/client/src/components/@commons/CardListItem.tsx
src/main/client/src/components/@commons/CustomBreadcrumb.tsx
src/main/client/src/components/@commons/DataSheet.tsx
src/main/client/src/components/@commons/ExampleApiCallComponent.tsx
src/main/client/src/components/@commons/ImageCarousel.tsx
src/main/client/src/components/@commons/Schedule.tsx
src/main/client/src/components/@pages/AchievementCategoryList.tsx
src/main/client/src/components/@pages/AchievementCategoryPage.tsx
src/main/client/src/components/@pages/CommunityList.tsx
src/main/client/src/components/@pages/CommunityPage.tsx
src/main/client/src/components/@pages/ResortList.tsx
src/main/client/src/components/@pages/ResortPage.tsx
src/main/client/src/components/@pages/RiddleCategoryList.tsx

Key props and community logos fix

---

.gitattributes
src/main/client/.prettierrc.json
src/main/client/src/components/@commons/CustomBreadcrumb.tsx
src/main/client/src/components/@commons/DataSheet.tsx
src/main/client/src/components/@pages/CommunityPage.tsx
src/main/client/src/content/communities.ts
src/main/client/src/content/resorts.ts
src/main/client/src/types/Organization.ts
src/main/client/src/utils/customTheme.ts

Closes #195 
Closes #201 if you allow it
Tasty 🥪

CMSCH #195 Refactor Community and Resort page

---

src/main/client/src/components/@commons/DataSheet.tsx

org logo update

---

src/main/client/src/components/@commons/LinkButton.tsx
src/main/client/src/components/@pages/CommunityList.tsx
src/main/client/src/components/@pages/Home.tsx
src/main/client/src/utils/AuthContext.tsx

- closes #173
- closes #193 
- Deletes loggedIn cookie if login is invalid

Small fixes

---

src/main/client/src/components/@commons/DataSheet.tsx
src/main/client/src/components/@pages/ProfilePage.tsx
src/main/client/src/components/@pages/QRList.tsx
src/main/client/src/components/@pages/RiddleCategoryList.tsx

Small fixes again

---

src/main/client/src/content/communities.ts

Added missing https to community website links

---

src/main/client/src/components/@pages/CommunityPage.tsx
src/main/client/src/components/@pages/ResortPage.tsx
src/main/client/src/content/communities.ts
src/main/client/src/content/resorts.ts

Please check that our community has proper images.
Also, We must use warp next year, downloading and migration images was so frustrating 😢 
Videos has not been solved yet.

Images, finally

---

src/main/client/src/content/communities.ts

CMSCH #237 Add Langosch to communities

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/ComponentApiBase.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/MenuItem.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/StylingComponent.kt

#336 Add styling component properties

---

frontend/src/pages/task/task.page.tsx
frontend/src/pages/task/taskCategory.page.tsx

added frontend support for expired tasks

---

backend/src/main/kotlin/hu/bme/sch/cmsch/config/TestConfig.kt
frontend/src/api/contexts/config/types.ts
frontend/src/pages/task/components/CodeEditor.tsx
frontend/src/pages/task/components/CustomForm.tsx
frontend/src/pages/task/components/InputWithAddon.tsx
frontend/src/pages/task/components/TaskCategoryListIem.tsx
frontend/src/pages/task/task.page.tsx
frontend/src/pages/task/taskCategory.page.tsx
frontend/src/pages/task/taskCategoryList.page.tsx
frontend/src/util/views/task.view.ts

- Fields in a custom form are no longer required, you can submit them empty
- If the suffix is specified in a custom form, it appears as an addon in right side of the input field
- more coding languages
- profileRequired task categories at the top, seperated from the rest
- New test data
- we still need an alert on the profile, that should be implemented in #359
- Closes #361

Final fixes for tasks

---

frontend/src/App.tsx
frontend/src/pages/error/unauthorized.page.tsx
frontend/src/pages/events/event.page.tsx
frontend/src/pages/events/eventList.page.tsx
frontend/src/pages/extra/extra.page.tsx
frontend/src/pages/form/components/autoFormField.tsx
frontend/src/pages/form/form.page.tsx
frontend/src/pages/login/login.page.tsx
frontend/src/pages/news/news.page.tsx
frontend/src/pages/news/newsList.page.tsx
frontend/src/pages/profile/profile.page.tsx
frontend/src/pages/riddle/riddle.page.tsx
frontend/src/pages/riddle/riddleList.page.tsx
frontend/src/pages/task/components/TaskStatusBadge.tsx
frontend/src/pages/task/task.page.tsx
frontend/src/pages/task/util/taskSubmissionResponseMap.ts
frontend/src/pages/token/components/QRScanResultComponent.tsx
frontend/src/pages/token/tokenList.page.tsx
frontend/src/pages/token/tokenScan.page.tsx

Rewritten all const strings in frontend code to use formal language
One question is still stays unanswered: do we include the link for our site (kir-dev.sch.bme.hu) because it uses informal language everywhere
This PR targets fixes/382-small-ui-changes branch, TAKE THIS INTO CONSIDERATION

Fix language

---

frontend/src/api/contexts/cookie-consent/CookieConsentContext.tsx
frontend/src/api/contexts/themeConfig/ThemeConfig.tsx
frontend/src/common-components/navigation/Navbar.tsx
frontend/src/util/configs/environment.config.ts

Dinamically set via setColorMode hook by chakra-ui

Force darkmode fix

---

frontend/src/pages/countdown/components/clock.tsx

Interval switcharoo

---

frontend/src/api/contexts/config/types.ts
frontend/src/pages/events/components/EventList.tsx
frontend/src/pages/news/components/NewsList.tsx
frontend/src/pages/news/components/NewsListItem.tsx

Support news component showDetails

---

frontend/src/api/contexts/config/types.ts
frontend/src/common-components/cmsch-ui-renderer.tsx
frontend/src/pages/task/components/CustomForm.tsx
frontend/src/pages/task/task.page.tsx
frontend/src/util/views/task.view.ts

Resubmission and other task fixes

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/signup/NovaIntegrationController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/signup/NovaIntegrationService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/SubmittedTaskEntity.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/SubmittedTaskEntityDto.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/TasksService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/controller/MainApiController.kt

#413 Task entity lob answer

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/TaskAdminRateController.kt
frontend/src/api/contexts/config/types.ts
frontend/src/common-components/footer/Footer.tsx

ain't nobody got time for review

Footer changes

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/token/TokenComponent.kt
frontend/src/api/contexts/config/types.ts
frontend/src/common-components/PresenceAlert.tsx
frontend/src/pages/profile/profile.page.tsx
frontend/src/pages/token/components/QRScanResultComponent.tsx
frontend/src/pages/token/components/StampComponent.tsx
frontend/src/pages/token/tokenList.page.tsx
frontend/src/util/configs/theme.config.ts
frontend/src/util/views/token.view.ts

token fixes

---

backend/build.gradle.kts
backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/ApplicationComponent.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/location/LocationApiController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/location/LocationComponent.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/location/RawLocationController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/location/TrackingMapController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/TaskAdminRateController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/controller/admin/BasicAdminController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/model/UserEntity.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/service/AdminMenuService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/util/Utility.kt
backend/src/main/resources/static/style.css
backend/src/main/resources/static/tracker.css
backend/src/main/resources/templates/admin.html
backend/src/main/resources/templates/details.html
backend/src/main/resources/templates/layout.html
backend/src/main/resources/templates/tracker.html

#427 Admin panel refactor

---

frontend/src/pages/profile/components/MapContainer.tsx
frontend/src/pages/profile/profile.page.tsx

lazy load the map component

---

frontend/src/pages/events/components/CardListItem.tsx
frontend/src/pages/events/components/CurrentEvent.tsx
frontend/src/pages/events/components/CustomTab.tsx
frontend/src/pages/events/components/EventList.tsx
frontend/src/pages/events/components/EventListItem.tsx
frontend/src/pages/events/eventList.page.tsx
frontend/src/pages/task/components/TaskCategoryListIem.tsx
frontend/src/pages/task/task.page.tsx
frontend/src/pages/task/taskCategory.page.tsx
frontend/src/util/core-functions.util.ts

- past events are hidden. They can be found under the Korábbi box if filtered by date
- weekdays are included in the dates, except for multiday events, cuz it would be too long
- ui and color fixes
- events in one column
~TODO:
event timeline~
Closes #448

event fixes

---

frontend/src/pages/teams/components/MemberRow.tsx

Admin renamed to Csapatkapitány

Admin renamed to Csapatkapitány

---

frontend/src/pages/task/components/TaskStatusBadge.tsx

TaskStatusBadge color change

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceApiController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceService.kt
frontend/src/api/contexts/config/types.ts
frontend/src/api/hooks/useRaceQuery.ts
frontend/src/pages/race/race.page.tsx
frontend/src/route-modules/Race.module.tsx
frontend/src/util/views/race.view.ts

When going to a not existing race url (  /race/asd  ) it should come back with a page doesnt exist error insted of a race called "not found". @Gerviba please fix this on the backend.

custum sormeresek

---

frontend/package.json
frontend/yarn.lock

Solves the webpack warning issue.
- closes #370

Code editor package update

---

frontend/src/common-components/ConfirmDialogButton.tsx
frontend/src/pages/riddle/riddle.page.tsx

New component: button with confirmation alert.
The alert is in the middle of the screen, the other box behind it doesn't include the scrollbar, that's why it is a bit off.
But I think it's fine. 
closes #528

Riddle hint alert

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/gallery/PhotoUploadController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/controller/admin/FileUploadController.kt
backend/src/main/resources/templates/uploadFile.html
backend/src/main/resources/templates/uploadPhoto.html

Implement batch file uploads

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormElement.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormGridTypes.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormService.kt
frontend/src/pages/form/components/GridField.tsx
frontend/src/pages/form/components/GridFieldItem.tsx
frontend/src/pages/form/components/autoFormField.tsx
frontend/src/pages/form/form.page.tsx
frontend/src/util/core-functions.util.ts
frontend/src/util/views/form.view.ts

GridFormFields

---

frontend/src/common-components/QrReader.tsx

Fix camera being left on after leaving QR page

---

backend/Dockerfile-build
backend/src/main/resources/config/application-prewarm.properties

Enable class data sharing in Docker images

---

backend/src/main/kotlin/hu/bme/sch/cmsch/config/TestConfig.kt
frontend/src/common-components/CollapsableTableRow.tsx
frontend/src/common-components/LeaderboardTable.tsx
frontend/src/common-components/layout/CmschContainer.tsx
frontend/src/pages/leader-board/leaderboard.page.tsx
frontend/src/pages/leader-board/leaderboardByCategory.page.tsx
frontend/src/pages/leader-board/leaderboardByUserOrGroup.page.tsx
frontend/src/route-modules/LeaderBoard.module.tsx

| Before                                                                                                                 | After                                                                                                                  |
| ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------- |
| ![Screen Shot 2024-08-24 at 15 22 39](https://github.com/user-attachments/assets/a084ccf9-1bff-411c-b010-f83d45283c94) | ![Screen Shot 2024-08-24 at 15 22 36](https://github.com/user-attachments/assets/cc828989-3b14-4400-9b1d-af4320ffd627) |
| ![Screen Shot 2024-08-24 at 15 23 …

Redesign leaderboard page

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/team/TeamIntroductionEntity.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/team/TeamIntroductionRepository.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/team/TeamIntroductionReviewController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/team/TeamService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/team/TeamView.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/config/SecurityConfig.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/model/GroupEntity.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/service/PermissionsService.kt
frontend/src/pages/teams/components/TeamDetailsCore.tsx
frontend/src/pages/teams/components/TeamListItem.tsx
frontend/src/pages/teams/editMyTeam.page.tsx
frontend/src/util/views/team.view.ts

Require review for team introductions

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleBusinessLogicService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleCategoryDto.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleComponent.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleSubmissionView.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleView.kt
frontend/src/pages/riddle/components/RiddleListItem.tsx
frontend/src/pages/riddle/riddle.page.tsx
frontend/src/pages/riddle/riddleCategory.page.tsx
frontend/src/pages/riddle/riddleList.page.tsx
frontend/src/route-modules/Riddle.module.tsx
frontend/src/util/views/riddle.view.ts

Make multiple riddles solveable

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/leaderboard/LeaderBoardComponent.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/leaderboard/LeaderBoardService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddlesByGroupsController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/Util.kt
frontend/src/api/contexts/config/types.ts
frontend/src/api/contexts/themeConfig/ThemeConfig.tsx
frontend/src/common-components/CollapsableTableRow.tsx
frontend/src/common-components/TokenRarityDisplay.tsx
frontend/src/pages/leader-board/leaderboard.page.tsx
frontend/src/util/views/leaderBoardView.ts

Add leaderboard token rarity display

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/communities/CommunitiesApiController.kt

#854 - sorted returned communities on backend

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleBusinessLogicService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleEntity.kt

split solution options with ;

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/conference/ConferencePresentationEntity.kt

Finally removed the need for proto endpoints at conference pauses.

removed the need for proto

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/profile/ProfileComponent.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/profile/ProfileService.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/profile/ProfileView.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/FreestyleRaceRecordRepository.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceService.kt
frontend/src/api/contexts/config/types.ts
frontend/src/pages/profile/components/ProfileQR.tsx
frontend/src/pages/profile/profile.groupChange.page.tsx
frontend/src/pages/profile/profile.page.tsx
frontend/src/pages/profile/util/percentFunctions.ts
frontend/src/util/views/profile.view.ts

Closes #932 
The race stat is displayed with it's time and placement.
The freestyle race appears with it's time and description/type
Preview:

feat: race and funky race stats on profile

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/TasksService.kt
backend/src/main/resources/config/application.properties
frontend/src/pages/task/task.page.tsx

Add image optimization on the client when submitting tasks

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/challenge/ChallengeController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/FreestyleRaceRecordController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/FreestyleRaceRecordEntity.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceRecordController.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceRecordEntity.kt

Propsed fix for not being able to search on the dropdown menu of user names. I simply swapped the ID and the name on the display, and changed the save function to look for the ID there.

fix: altered the view of the user name dropdown menu to allow search

---

backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/FreestyleRaceEntryDto.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/FreestyleRaceRecordEntity.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceEntryDto.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceRecordEntity.kt
backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceService.kt
frontend/src/pages/teams/teamList.page.tsx

Closes #966 
As requested, I removed the label from freestyle race entries and applied it to the normal races instead. It also now takes labels into consideration when searching for teams or within labels.

feat: race label + group and race label search
