- src/main/client/package.json
- src/main/client/src/App.tsx
- src/main/client/src/components/@commons/QRScanResultComponent.tsx
- src/main/client/src/components/@commons/QrScanResultComponent.tsx
- src/main/client/src/components/@commons/StampComponent.tsx
- src/main/client/src/components/@pages/QRList.tsx
- src/main/client/src/components/@pages/QRScan.tsx
- src/main/client/src/components/@pages/QRScanResult.tsx
- src/main/client/src/types/dto/profile.ts
- src/main/client/src/types/dto/token.ts
- src/main/client/src/utils/navItems.ts
- src/main/client/yarn.lock
Done the views for token collection:
- Show progress, and list already scanned codes
- Scan new qr code
- Redirect page for manual 
Wired in axios requests in the list view and scan view, but i think we should outsource the api communication in  a service file and handle network errors in one place, that way the pages would look nicer, and the error handling would be the same across the site.
I didn't use the [recommended](https://github.com/nimiq/qr-scanner) QR lib, because i would have to manually wire in a service worker js file, but the `react-qr-reader` package does it for me. 
The QR reader right now won't work because there is a bug on backend side with the post API.
!! 
> Due to browser implementations the camera can only be accessed over https or localhost.
closes #33 
closes #12
> Qr code pages

- src/main/client/src/utils/Loading.tsx
Added the component that show a spinner or a given component after the given timeout or one second.
Default usage: `<Loading />`
Advanced usage: `<Loading timeout={5}><your loading component, i.e. Skeleton></Loading>`
> Added Loading component

- src/main/client/src/components/@commons/CustomBreadcrumb.tsx
- src/main/client/src/components/@pages/AchievementCategoryList.tsx
- src/main/client/src/components/@pages/AchievementCategoryPage.tsx
- src/main/client/src/components/@pages/AchievementPage.tsx
- src/main/client/src/components/@pages/CommunityPage.tsx
- src/main/client/src/components/@pages/ResortPage.tsx
- src/main/client/src/types/dto/achievements.ts
- src/main/client/src/utils/customTheme.ts
- src/main/client/src/utils/utilFunctions.ts
- removed the different colors from the Breadcrumbs on the resort and community pages, it always uses the brand color
- Added an infobox to the achievement submission form that shows the submission deadline
- It uses the date formatter function from #109 
- redefined the colors of solid buttons in darkmode globally. In `customTheme.ts` I overrode the function that generates the color values for solid buttons (I copied the function from the chakra source code and changed some values to make the buttons darker in darkMode)
Before and after: (there was no change in lightmode or to the outline variants)
> Breadcrumb, achievement submission date and darkmode buttons fix

- src/main/client/src/components/@commons/CustomBreadcrumb.tsx
- src/main/client/src/components/@commons/QRScanResultComponent.tsx
- src/main/client/src/components/@commons/Schedule.tsx
- src/main/client/src/components/@commons/StampComponent.tsx
- src/main/client/src/components/@layout/Footer.tsx
- src/main/client/src/components/@layout/navigation/DesktopNav.tsx
- src/main/client/src/components/@layout/navigation/Navbar.tsx
- src/main/client/src/components/@pages/AchievementCategoryList.tsx
- src/main/client/src/components/@pages/Home.tsx
- src/main/client/src/components/@pages/ProfilePage.tsx
- src/main/client/src/utils/Loading.tsx
- src/main/client/src/utils/customTheme.ts
- Everything that's green on the site uses 'brand.500' in light mode and 'brand.600' in dark mode.
- The only exception is the hover of the achievement and riddle items, that remained 'brand.300' and 'brand.700' (the default colors would be too vibrant here because these are pretty big)
- Had to overwrite the ghost and outline variants of the Button component, the subtle variant of the Alert component (because Toast uses this), and the Progress component.
- Outline and ghost variants of Button have a subtle hover color
- The button that toggles the Navbar on mobile is no longer green, but the default color like the button that toggles the theme
- Closes #206 
The QR-stamps button is hovered
> Consistent green colors

- src/main/client/src/components/@pages/ProfilePage.tsx
- src/main/client/src/content/communities.ts
- Closes #223
- 0% instead of NaN% on the profile page for riddles and qr codes as well (#226 only fixed it for bucketlist)
> kszk signup links and no more NaN on profile page

- src/main/client/src/components/@pages/ProfilePage.tsx
- src/main/client/src/components/@pages/QRList.tsx
- src/main/client/src/types/dto/profile.ts
`collectedTokenCount` wasn't even used in the frontend before
There are 4 default and one extra token in the mock data, and this is how it looks after scanning one default and one extra:
> Count only the default tokens in progress

- src/main/client/src/content/communities.ts
Missing https:// caused the link to navigate internally (idk why, it is supposed to be external) Checked all links now.
> Fixed missing protocol in link

- frontend/src/api/contexts/auth/AuthContext.tsx
Closes #383 
Idk if it solves the issue, pls someone fix it, or give more context for me to solve the issue (i dont even know where it caused an issue)
Right now it only refreshes the token on first content paint (when the page loads in, AND ONLY ONCE for the whole usage of the site).
One more thing: the PR targets fixes/382-small-ui-changes branch, not staging, not master as of now (can be changed)
> Refresh token

- frontend/src/pages/home/home.page.tsx
- frontend/src/pages/impressum/impressum.page.tsx
Target branch: only the `deploy/hackathon-live`, we need this information on the front page.
> Move organizers to home page

- frontend/src/api/contexts/config/types.ts
- frontend/src/api/contexts/themeConfig/ThemeConfig.tsx
- frontend/src/common-components/chakra-md-renderer.tsx
- frontend/src/common-components/footer/Footer.tsx
- frontend/src/common-components/navigation/Navbar.tsx
- frontend/src/pages/access-key/accessKey.page.tsx
- frontend/src/pages/communities/communityList.page.tsx
- frontend/src/pages/communities/organizationList.page.tsx
- frontend/src/pages/error/error.page.tsx
- frontend/src/pages/error/unauthorized.page.tsx
- frontend/src/pages/events/components/event-calendar/DayCalendar.tsx
- frontend/src/pages/events/components/event-calendar/WeekCalendar.tsx
- frontend/src/pages/events/components/event-calendar/ZoomBar.tsx
- frontend/src/pages/events/eventCalendar.page.tsx
- frontend/src/pages/events/eventList.page.tsx
- frontend/src/pages/extra/extra.page.tsx
- frontend/src/pages/form/form.page.tsx
- frontend/src/pages/home/home.page.tsx
- frontend/src/pages/impressum/impressum.page.tsx
- frontend/src/pages/leader-board/leaderBoard.page.tsx
- frontend/src/pages/leader-board/leaderBoardCategory.page.tsx
- frontend/src/pages/map/map.page.tsx
- frontend/src/pages/news/components/NewsList.tsx
- frontend/src/pages/qr-fight/qrLevels.page.tsx
- frontend/src/pages/race/components/RaceBoard.tsx
- frontend/src/pages/riddle/riddleHistory.page.tsx
- frontend/src/pages/riddle/riddleList.page.tsx
- frontend/src/pages/task/taskCategoryList.page.tsx
- frontend/src/pages/teams/teamList.page.tsx
- frontend/src/pages/token/tokenList.page.tsx
- Transparent footer, if enabled on the backend
- Transparent navbar, if enabled on the backend
- Buttons in the event component now use the brand color
- page titles (with no user-defined text) promoted to h1. 
- headings no longer use the display font. Created a new Chakra Heading variant that uses the display font. Applied this variant to all h1 headings
> More navbar & footer styling  options - frontend

- backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/ComponentSettingEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/bmejegy/BmejegyRecordEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/communities/CommunityEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/communities/OrganizationEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/conference/ConferenceEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/conference/ConferencePresentationEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/debt/ProductEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/debt/SoldProductEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/email/EmailTemplateEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/event/EventEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/ResponseEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/location/LocationEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/location/WaypointEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/news/NewsEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/proto/ProtoEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/qrfight/QrLevelEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/qrfight/QrTowerEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceCategoryEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/riddle/RiddleEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/staticpage/StaticPageEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/SubmittedTaskEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/TaskCategoryEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/TaskEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/token/TokenEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/model/GroupEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/model/UserDetailsByInternalIdMappingEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/model/UserEntity.kt
There are no invalid sql statement errors at startup anymore.
With Postgres, this is the DDL diff (in the previous version the 'create table' for bmejegy failed)
> create table bmejegy_records
> (
>     id              integer               not null
>         primary key,
>     date            varchar(255)          not null,
>     email           varchar(255)          not null,
>     faculty         varchar(255)          not null,
>     full_name       varchar(255)          not null,
>     id_id           varchar(255)          not null,
>     item            varchar(255)          not null,
>     item_id         varchar(255)          not null,
>     matched_user_id integer               not null,
>     order_key       varchar(255)          not null,
>     photo_id        varchar(255) …
> Improve entity definition

- backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/ExtraMenuController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/MenuService.kt
The app navbar is now refreshed when an extra-menu is added, removed or edited
Fixes #732
> Refresh navbar cache after extra-menu modification

- backend/src/main/kotlin/hu/bme/sch/cmsch/component/login/AuthschLoginController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/config/WebMvcConfig.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/service/JwtTokenProvider.kt
- frontend/src/api/contexts/auth/AuthContext.tsx
- frontend/src/api/hooks/profile/useProfileQuery.ts
- frontend/src/api/hooks/useTokenRefresh.ts
- frontend/src/pages/form/form.page.tsx
- frontend/src/pages/index/index.page.tsx
- frontend/src/pages/teams/createTeam.page.tsx
- frontend/src/pages/teams/editMyTeam.page.tsx
- frontend/src/util/configs/api.config.ts
With this PR approved, the backend will start to set cookies for the domain from the site url, making cookies HTTP only and Secure, removing the need to manually get the JWT from the query param and state manage from there.
I made sure to handle the refresh mechanism for Create & Edit team flows as well as form submission.
Logout works as well by setting the cookie to null.
> feat: add secure cookie based auth

- backend/src/main/kotlin/hu/bme/sch/cmsch/admin/GenerateOverview.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/admin/OverviewBuilder.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/MenuAdminController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/task/TaskAdminRateController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/controller/admin/FilesByViewController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/controller/admin/OneDeepEntityPage.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/controller/admin/TwoDeepEntityPage.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/controller/auditlog/AuditLogController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/controller/userhandling/PermissionGroupAssignPage.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/controller/userhandling/PermissionGroupUserListPage.kt
- backend/src/main/resources/templates/overview4.html
> Make overview template more robust

- frontend/src/pages/riddle/riddle.page.tsx
After the user submits the riddle, and it was not correct, the ref to the solutionInput gets focused.
After using the riddles a few times, I noticed that I always had to click back to the input field, after submitting the riddle, even when I didn't press the Submit button, but pressed Enter. This should fix that.
> Focus input after submitting riddle

- frontend/src/common-components/layout/AppBackground.tsx
added quick fix to use mobile background on smaller screens
This might not be the best way to do it, since the screen's size is only checked once, on the component's load.  
A resize event handler could be added to make it responsive, but I'm not sure if that's needed.
> Fix Mobile background on smaller screens

- .github/workflows/build-release.yml
Release docker images will now only be built when manually triggered or when creating a version tag.
When using a tag starting with `v`, the image will be tagged with it.
> Update release trigger to manual or tag, tag image with version

- backend/build.gradle.kts
- backend/src/main/kotlin/hu/bme/sch/cmsch/admin/OverviewBuilder.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/admission/AdmissionApiController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/app/ApplicationApiController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/email/EmailService.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormApiController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormElement.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormService.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/ResponseEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/ResponseRepository.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/sheets/SheetsFormsListener.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/config/TestConfig.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/extending/FormSubmissionListener.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/service/UserProfileGeneratorService.kt
- frontend/src/pages/form/form.page.tsx
> Allow users to fill out forms as GUEST and send email responses

- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormApiController.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/FormService.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/form/ResponseEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/config/TestConfig.kt
When a lot of concurrent calls hit the endpoint, some of the users got multiple emails, because some of the transactions got rolled back and retried. In this PR I moved the email sending API call outside of the database transaction
> Move api call out of transaction to prevent calling it multiple times

- backend/src/main/kotlin/hu/bme/sch/cmsch/component/event/EventEntity.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/news/NewsEntity.kt
Needed for tracking by StartSCH.
This should add the `id` field to the entities returned by `/api/news` and `/api/events`.
> Expose IDs for events and news

- backend/src/main/kotlin/hu/bme/sch/cmsch/component/profile/ProfileService.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/profile/ProfileView.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceService.kt
- backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceStatsView.kt
- frontend/src/pages/profile/profile.page.tsx
- frontend/src/util/views/profile.view.ts
Closes #967 
As requested by the organizers, I added a few more statistics to the page. They also declared that displaying the freestyle race statistics were unnecessary, so I removed it. It looks like this now:
> feat: detailed race statistics on profile

- backend/src/main/kotlin/hu/bme/sch/cmsch/component/race/RaceService.kt
I mistakenly checked the best time of all users, for the user, therefore it always returned the globally best time.
I also accidentally checked the placement, based on all records in the database (If person A had 2 records where both had better time than you, it accounted both for the placement)
Both these errors should be fixed now
> fixed an oversight with the best time and placement evaluation
